server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: exchange-service
          uri: https://stunning-celebration-production-3657.up.railway.app
          predicates:
            - Path=/exchange-service/{segment}
          filters:
            - SetPath=/{segment}

        - id: converter-service
          uri: https://courageous-enjoyment-production-a711.up.railway.app
          predicates:
            - Path=/converter-service/{segment}
          filters:
            - SetPath=/{segment}